version: '3.4'
services:
  app:
    build:
      context: .
    env_file:
      - ./compose/postgres.env
    environment:
      MIX_BUILD_PATH: /mix/build
      MIX_DEPS_PATH: /mix/deps
    volumes:
      - .:/opt/app:z
      - deps:/mix/deps:Z
      - build:/mix/build:Z
      - ./animals.csv:/files/animals.csv
    depends_on:
      - db
  db:
    image: postgres:10
    env_file:
      - ./compose/postgres.env
    volumes:
      - /var/lib/postgresql
    ports:
      - 5432:5432
volumes:
  deps: {}
  build: {}